config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :trains
  resources :cars
  resources :routes
  resources :stations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  include Typeof
  scope :unused, -> { where(train_id: nil) }
  scope :all_cars, ->(train) { where(type_of: train.type_of).where(train_id: [train.id, nil]) }
end

app/models/concerns/typeof.rb
module Typeof
  extend ActiveSupport::Concern
  included do
    enum :type_of, {passenger: 0, cargo: 1}, default: :passenger
  end
  class_methods do
  end
end

app/models/route.rb
class Route < ApplicationRecord
  has_and_belongs_to_many :stations
  has_many :trains
end

app/models/station.rb
class Station < ApplicationRecord
  has_many :trains
  has_and_belongs_to_many :routes
end

app/models/train.rb
class Train < ApplicationRecord
  include Typeof
  belongs_to :route
  has_many :cars

  validate :validate_cars

  def validate_cars
    errors.add(:cars, "too mutch") if cars.size > car_max
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[show edit update destroy]
  def index
    @cars = Car.all
    @car_cargo = @cars.cargo
    @car_passenger = @cars.passenger
  end

  def show
  end

  def new
    @car = Car.new
  end

  def edit
  end

  def create
    @car = Car.new(car_params)
    respond_to do |format|
      if @car.save
        format.html { redirect_to cars_path, notice: t("general.sucsessfully_create_msg") }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to cars_path, notice: t("general.successfully_update_msg") }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to car_path, notice: t("general.success_destroy: #{@car.number}") }
    end
  end

  private

  def set_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:number, :type_of)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: %i[show edit update destroy]
  def index
    @routs = Route.all
  end

  def show
  end

  def new
    @route = Route.new
  end

  def edit
  end

  def create
    @route = Route.new(route_params)
    respond_to do |format|
      if @route.save
        format.html { redirect_to routes_path, notice: t("general.sucsessfully_create_msg") }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to routes_path, notice: t("general.successfully_update_msg") }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to route_path, notice: t("general.success_destroy: #{@route.name}") }
    end
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:name, station_ids: [])
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: %i[show edit update destroy]
  def index
    @stations = Station.all
  end

  def show
  end

  def new
    @station = Station.new
  end

  def edit
  end

  def create
    @station = Station.new(station_params)
    respond_to do |format|
      if @station.save
        format.html { redirect_to stations_path, notice: t("general.sucsessfully_create_msg") }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to stations_path, notice: t("general.successfully_update_msg") }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to station_path, notice: t("general.success_destroy: #{@station.name}") }
    end
  end

  private

  def set_station
    @station = Station.find(params[:id])
  end

  def station_params
    params.require(:station).permit(:name)
  end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: %i[show edit update destroy]
  def index
    @trains = Train.all.includes([:route])
    @train_cargo = @trains.cargo
    @train_passenger = @trains.passenger
  end

  def show
    @station = Station.find(@train.station_id) if @train.station_id
    @route = Route.includes([:stations]).find(@train.route.id)
    @all_stations = @route.stations[0..]
  end

  def new
    @train = Train.new
  end

  def edit
    if @train.cargo?
      @cars = Car.cargo.where(status: "free")
    elsif @train.passenger?
      @cars = Car.passenger.where(status: "free")
    end
  end

  def create
    @train = Train.new(train_params)
    respond_to do |format|
      if @train.save
        format.html { redirect_to trains_path, notice: t("general.sucsessfully_create_msg") }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to trains_path, notice: t("general.successfully_update_msg") }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @train.destroy
    respond_to do |format|
      format.html { redirect_to train_path, notice: t("general.success_destroy: #{@train.name}") }
    end
  end

  private

  def set_train
    @train = Train.find(params[:id])
  end

  def train_params
    params.require(:train).permit(:number, :car_max, :route_id, :station_id, :type_of, car_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def station_prev_next(station_name, route)
    "Prev - Next: #{prev_station(station_name, route)} - #{next_station(station_name, route)}"
  end

  def prev_station(station_name, route)
    @all_stations[get_station_id(station_name, route) - 1]&.name if (get_station_id(station_name, route) - 1) >= 0
  end

  def next_station(station_name, route)
    @all_stations[get_station_id(station_name, route) + 1]&.name if (get_station_id(station_name, route) - 1) <= route.stations.size
  end

  def get_station_id(station_name, route)
    id = 0
    route.stations.each_with_index do |station, i|
      id = i if station.name == station_name
    end
    id
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cars/_car.html.erb
<tr >
  <td class="bg-gray-100 px-2 py-2"><%= link_to car.number, car_path(car) %></td>
  <td class="px-2 py-2"><%= car.type_of %></td>
  <td class="px-2 py-2"><%= car.train_id %></td>
  <td class="bg-gray-100 px-2 py-2"><%=  car.train_id.nil? ? t('.unchained') : t('.chained')%></td>
  <td class="px-2 py-2"><%= link_to t('general.edit'), edit_car_path(car) %> | <%= link_to t("general.remove"), car_path(car), data: {"turbo-method": :delete}, form: { data: { turbo_confirm: "Are you sure?" } }  %> </td>
</tr>

app/views/cars/_form.html.erb
<%= simple_form_for (@car) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs pb-[200px]">
    <div class="mb-6">
      <h4 class="mb-2"><%= f.label :number, t('.number') %></h4>
      <div>
        <%= f.input :number,
          label: false,
          input_html: {
            class: "input input-sm w-full",
            placeholder: t('general.text_placeholder')
          } %>
      </div>
    </div>
    <div class="">
      <h4 class="mb-2"><%= f.label :type_of, t('.type_of') %></h4>
      <div class="select-sm w-[300px]">
        <%= f.input :type_of,
          label: false,
          collection: Car.type_ofs.keys
           %>
      </div>
    </div>
    <div class="py-2">
      
    <%= link_to t('general.cancel'), :back%>
    <%= f.submit t('general.save'), class: "group relative w-200 justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
    </div>
  </div>
<% end %>

app/views/cars/edit.html.erb
<div>
  <%= render "form", train: @train %>
</div>

app/views/cars/index.html.erb
<div>
  <%= link_to t('general.add'), new_car_url, class: "group relative w-200 justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"%>
</div>

<table class="w-full divide-y divide-gray-300">
  <thead>
    <tr>
      <th><%= t('.car_number') %></th>
      <th><%= t('.type_of') %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "car", collection: @cars %>
  </tbody>
</table>

app/views/cars/new.html.erb
<div>
<%= render "form" %>
</div>

app/views/cars/show.html.erb
<div class="bg-white shadow overflow-hidden sm:rounded-lg">
  <div class="px-4 py-5 sm:px-6">
    <h3 class="text-lg leading-6 font-medium text-gray-900"><%= t('.cars_information') %></h3>
    <p class="mt-1 max-w-2xl text-sm text-gray-500"><%= t('.car_details') %></p>
  </div>
  <div class="border-t border-gray-200">
     <dl>
      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500"><%= t('.car_number') %>: </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= @car.number %></dd>
      </div>
      <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500"><%= t('.type_of') %>: </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= t(".#{@car.type_of}") %></dd>
      </div>
  </div>
  <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
    
  <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= link_to t("general.back"), :back %></dd>
  </div>
     </dl>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
some text some input/output

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trainlist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body > 


    <%= render "shared/nav" %>
    <div class="bg-gray-200 py-5 ">
      <main class="container mx-auto px-4 py-4 bg-white rounded-lg h-full">
        <%= yield %>
      </main>
    </div>

  </body>
</html>

app/views/routes/_form.html.erb
<%= simple_form_for (@route) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs pb-[200px]">
    <div class="mb-6">
      <h4 class="mb-2"><%= f.label :name, t('.name') %></h4>
      <div>
        <%= f.input :name,
          label: false,
          input_html: {
            class: "focus:ring-indigo-500 focus:border-indigo-500 flex-1 block w-full px-2 rounded-md sm:text-sm border-gray-300 input input-sm w-full",
            placeholder: t('general.text_placeholder')
          } %>
      </div>
    </div>
    <div class="">
      <h4 class="mb-2"><%= f.label :station, t('.stations') %></h4>
      <div class="select-sm w-[300px]">
        <%= f.association :stations, collection: Station.all, label: false, label_method: :name, as: :check_boxes %> 
      </div>
    </div>
    <div class="px-2">
      <%= link_to t('general.cancel'), :back%>
      <%= f.submit t('general.save'), class: "group relative w-200 justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
    </div>
  </div>
<% end %>

app/views/routes/_route.html.erb
<tr >
  <td class="bg-gray-100 px-2 py-2"><%= link_to route.name, route_path(route) %></td>
  <td class="px-2 py-2">
    <ul>
      <% route.stations.each do |station| %>
        <li><%= station.name %></li>
      <% end %>
    </ul>
  </td>
  <td class="bg-gray-100 px-2 py-2"><%= link_to t('general.edit'), edit_route_path(route) %> | <%= link_to t("general.remove"), route_path(route), data: {"turbo-method": :delete}, form: { data: { turbo_confirm: "Are you sure?" } }  %> </td>
</tr>

app/views/routes/edit.html.erb
<div>
  <%= render "form", train: @train %>
</div>

app/views/routes/index.html.erb
<table class="w-full divide-y divide-gray-300">
  <thead>
    <tr>
      <th><%= t('.route_name') %></th>
      <th><%= t('.stations') %></th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "route", collection: @routs %>
  </tbody>
</table>

app/views/routes/new.html.erb
<div>
<%= render "form" %>
</div>

app/views/routes/show.html.erb
<div class="bg-white shadow overflow-hidden sm:rounded-lg">
  <div class="px-4 py-5 sm:px-6">
    <h3 class="text-lg leading-6 font-medium text-gray-900"><%= t('.route_information') %></h3>
    <p class="mt-1 max-w-2xl text-sm text-gray-500"><%= t('.route_details') %></p>
  </div>
  <div class="border-t border-gray-200">
     <dl>
  <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
    <dt class="text-sm font-medium text-gray-500"><%= t(".route_name") %>:</dt>
    <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= @route.name %></dd>
  </div>
  <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
    <dt class="text-sm font-medium text-gray-500"><%= t('.stations') %>:</dt> 
    <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
      <% @route.stations.each_with_index do |station, i| %>
        <br><%= "#{i+1} - #{station.name}" %> 
      <% end %>
    </dd>
  </div>
  </div>
  <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
    <%= link_to t("general.back"), :back %>
  </div>

app/views/shared/_nav.html.erb
<header>
        <nav class="bg-white border-gray-200 px-4 lg:px-6 py-2.5 dark:bg-gray-800">
            <div class="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl">
                <a href="/" class="flex items-center">
                    <img src="https://flowbite.com/docs/images/logo.svg" class="mr-3 h-6 sm:h-9" alt='<%= t(".trains") %>' />
                    <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white"><%= t(".trains") %></span>
                </a>
                <div class="hidden justify-between items-center w-full lg:flex lg:w-auto lg:order-1" id="mobile-menu-2">
                    <ul class="flex flex-col mt-4 font-medium lg:flex-row lg:space-x-8 lg:mt-0">
                        <li>
                            <a href="/" class="block py-2 pr-4 pl-3 text-white rounded bg-blue-700 lg:bg-transparent lg:text-blue-700 lg:p-0 dark:text-white" aria-current="page"><%= t(".main") %></a>
                        </li>
                        <li>
                          <%= link_to t(".routes"), routes_path, class: "block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-blue-700 lg:p-0 dark:text-gray-400 lg:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700" %>
                        </li>
                        <li>
                          <%= link_to t(".trains"), trains_path, class: "block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-blue-700 lg:p-0 dark:text-gray-400 lg:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700" %>
                        </li>
                        <li>
                          <%= link_to t(".cars"), cars_path, class: "block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-blue-700 lg:p-0 dark:text-gray-400 lg:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700" %>
                        </li>
                        <li>
                          <%= link_to t(".stations"), stations_path, class: "block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-blue-700 lg:p-0 dark:text-gray-400 lg:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700" %>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    

app/views/stations/_form.html.erb
<%= simple_form_for (@station) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs pb-[200px]">
    <div class="mb-6">
      <h4 class="mb-2"><%= f.label :name, t('.name') %></h4>
      <div>
        <%= f.input :name,
          label: false,
          input_html: {
            class: "input input-sm w-full px-2",
            placeholder: t('general.text_placeholder')
          } %>
      </div>
    </div>
    <div class="px-2">
      <%= link_to t('general.cancel'), :back%>
      <%= f.submit t('general.save'), class: "group relative w-200 justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
    </div>
  </div>
<% end %>

app/views/stations/_station.html.erb
<tr >
  <td class="bg-gray-100 px-2 py-2"><%= link_to station.name, station_path(station)%></td>
  <td class="px-2 py-2">
    <ul>
      <% station.trains.each do |train| %>
        <li><%= train.number %></li>
      <% end %>
    </ul>
  </td>
  <td class="bg-gray-100 px-2 py-2">
    <ul>
      <% station.routes.each do |route| %>
        <ul>
          <li><%= route.name %></li>
        </ul>
      <% end %>
    </ul>
  </td>
  <td class="px-2 py-2">
    <%= link_to t('general.edit'), edit_station_path(station) %> | 
    <%= link_to t("general.remove"), station_path(station), data: {"turbo-method": :delete}, form: { data: { turbo_confirm: "Are you sure?" } }  %> 
  </td>
</tr>

app/views/stations/edit.html.erb
<div>
  <%= render "form", station: @station %>
</div>

app/views/stations/index.html.erb
<div>
  <%= link_to t('general.add'), new_station_url, class: "group relative w-200 justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"%>
</div>

<table class="w-full divide-y divide-gray-300">
  <thead>
    <tr>
      <th><%= t('.name') %></th>
      <th><%= t('.trains') %></th>
      <th><%= t('.route') %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "station", collection: @stations %>
  </tbody>
</table>

app/views/stations/new.html.erb
<div>
<%= render "form" %>
</div>

app/views/stations/show.html.erb
<div class="bg-white shadow overflow-hidden sm:rounded-lg">
  <div class="px-4 py-5 sm:px-6">
    <h3 class="text-lg leading-6 font-medium text-gray-900"><%= t('.stations_information') %></h3>
    <p class="mt-1 max-w-2xl text-sm text-gray-500"><%= t('.station_details') %></p>
  </div>
  <div class="border-t border-gray-200">
     <dl>
      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500"><%= t('.station_name') %>: </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= @station.name %></dd>
      </div>
      <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500"><%= t('.routes') %>: </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
          <% @station.routes.each do |route| %>
            <br><%= route.name %>
          <% end %>
        </dd>
      </div>
  </div>
  <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
    
  <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= link_to t("general.back"), :back %></dd>
  </div>
     </dl>
</div>

app/views/trains/_train.html.erb
<tr >
  <td class="bg-gray-100 px-2 py-2"><%= link_to train.number, train_path(train) %></td>
  <td class="px-2 py-2"><%= train.type_of %></td>
  <td class="bg-gray-100 px-2 py-2"><%= link_to train.route&.name, route_path(train.route)%></td>
  <td class="px-2 py-2">
    <ul>
      <% train.cars.each do |car| %>
        <li><%= car.number %></li>
      <% end %>
    </ul>
  </td>
  <td class="bg-gray-100 px-2 py-2"><%= train.car_max %></td>
  <td><%= link_to t('general.edit'), edit_train_path(train) %> | <%= link_to t("general.remove"), train_path(train), data: {"turbo-method": :delete}, form: { data: { turbo_confirm: "Are you sure?" } }  %> </td>
</tr>

app/views/trains/edit.html.erb
<div>
  <%= render "form", train: @train %>
</div>

app/views/trains/index.html.erb
<div>
  <%= link_to t('general.add'), new_train_url, class: "group relative w-200 justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"%>
</div>

<table class="w-full divide-y divide-gray-300">
  <thead>
    <tr>
      <th><%= t('.train_number') %></th>
      <th><%= t('.type_of') %></th>
      <th><%= t('.route') %></th>
      <th><%= t('.cars_list') %></th>
      <th><%= t('.max_cars') %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "train", collection: @trains %>
  </tbody>
</table>

app/views/trains/new.html.erb
<div>
<%= render "form" %>
</div>

app/views/trains/show.html.erb
<div class="bg-white shadow overflow-hidden sm:rounded-lg">
  <div class="px-4 py-5 sm:px-6">
    <h3 class="text-lg leading-6 font-medium text-gray-900"><%= t('.train_information') %></h3>
    <p class="mt-1 max-w-2xl text-sm text-gray-500"><%= t('.train_details') %></p>
  </div>
  <div class="border-t border-gray-200">
     <dl>
      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500"><%= t('.train_number') %>: </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= @train.number %></dd>
      </div>
      <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500"><%= t('.route_name') %>: </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= @train.route.name %></dd>
      </div>
      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500"><%= t('.max_cars') %>: </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= @train.car_max %></dd>
      </div>
      <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500"><%= t('.type_of') %>: </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= t(".#{@train.type_of}") %>
      </div>
      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500"><%= t('.current_station') %>: </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= @station&.name %>
      </div>
      <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500"><%= station_prev_next(@station&.name, @train.route) %></dt>
      </div>
    </div>
      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <%= link_to t("general.back"), :back %>
      </div>